# Generated by Django 3.0.5 on 2021-03-24 16:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('profation', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('distric', models.CharField(max_length=50)),
                ('gila', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('relegion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
