# Generated by Django 3.0.5 on 2021-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='address',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='country',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='distric',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='gila',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='name2',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='information',
            name='relegion',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='information',
            name='thana',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
