# Generated by Django 3.0.5 on 2021-03-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
