# Generated by Django 3.0.5 on 2021-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210324_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='distric',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='gila',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='name2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='information',
            name='relegion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='information',
            name='thana',
            field=models.CharField(max_length=50),
        ),
    ]
