# Generated by Django 3.0.5 on 2021-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210324_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='key',
            field=models.CharField(max_length=600, unique=True),
        ),
    ]
